### ISSUE TITLE
name of the streamer doesn't show up in emote tab if

### ISSUE THREAD

**Issue by AengusFalco** [fourtf/chatterino2#950] opened 2019-02-05 20:09 UTC
Name of the streamer doesn't show up in emote tab if the name is in japanese/chinese or whatever the heck that language is... 
Example - https://i.imgur.com/4fEKSLj.png
Bug itself - https://i.imgur.com/lx3QoXE.png

**Comment by Ckath** [comment] 2019-03-23 23:11
was going to look at this but I cant reproduce it, are you on latest? if this is fixed by now it can be closed
![image](https://user-images.githubusercontent.com/15038414/54872732-2f5e8680-4dc9-11e9-8a12-76fa4955f64f.png)

**Comment by pajlada** [comment] 2019-04-26 21:19
Feel free to reopen this if you can still reproduce it in the latest nightly (available under github releases).

**Closed by pajlada** 2019-04-26 21:19 UTC
