### ISSUE TITLE
Connecting and disconnecting a VPN while Chatterino is running causes it to stall.

### ISSUE THREAD

**Issue by coral** [fourtf/chatterino2#199] opened 2018-01-02 20:32 UTC
It does not reconnect.

**Comment by Cranken** [comment] 2018-04-02 14:11
Is this still happening? I can't reproduce it. Connecting to my uni vpn doesn't cause the program to stall. Are you sure it was just due to changing the network?

**Comment by fourtf** [comment] 2018-06-04 19:47
probably fixed now

**Closed by fourtf** 2018-06-04 19:47 UTC
Labels: bug
