### ISSUE TITLE
Removing a custom command crashes chatterino

### ISSUE THREAD

**Issue by Jarel1337** [fourtf/chatterino2#471] opened 2018-06-14 15:26 UTC
Steps to reproduce:

Open chatterino -> settings menu -> create command -> delete command = crash

log is:
```
chatterino: ../src/util/signalvector2.hpp:69: void chatterino::util::BaseSignalVector<TVectorItem>::removeItem(int, void*) [with TVectorItem = chatterino::controllers::commands::Command]: Assertion `index >= 0 && index < this->vector.size()' failed.
```

Tested on Gentoo Linux 
Head: 635d4b23416ecbed35256c1a206b85ae271318fb

**Comment by fourtf** [comment] 2018-06-14 15:31
duplicate of #456

**Closed by fourtf** 2018-06-14 15:31 UTC
