### ISSUE TITLE
Completion Tooltip from BTTV enhancement

### ISSUE THREAD

**Issue by praisethecherry** [fourtf/chatterino2#364] opened 2018-04-25 12:54 UTC
It would be nice if the function BetterTTV (Completion Tooltip) was added to Chatterino 2 
![tooltip](https://user-images.githubusercontent.com/38725354/39247024-e262975a-48a0-11e8-9da8-7459e29dae4c.png)
![tooltip2](https://user-images.githubusercontent.com/38725354/39247025-e2857180-48a0-11e8-965d-7d958c47d85b.png)
![tooltip3](https://user-images.githubusercontent.com/38725354/39247028-e2ab95ae-48a0-11e8-8a5e-029283d3ddb2.png)

Thanks for Chatterino

**Comment by notheowner** [comment] 2018-04-25 13:05
Make a toggle for it, not a big fan of it, I like the current tab complete implementation, without fancy UI etc. I like doing things fast

**Comment by fourtf** [comment] 2018-06-24 13:11
duplicate of #14

**Closed by fourtf** 2018-06-24 13:11 UTC
Labels: enhancement
