### ISSUE TITLE
Space between message elements too big (happens infrequently)

### ISSUE THREAD

**Issue by LajamerrMittesdine** [fourtf/chatterino2#552] opened 2018-07-02 09:53 UTC
This issue has happened 3 times so far. 2 times on Linux and 1 time on Windows so far for me. But days/weeks apart from each other.

Requires restart in order to go back to normal.

I'm not 100% sure on this but I think everytime this has happened to me it was when I was trying to switch tabs.

![image](https://user-images.githubusercontent.com/2313104/42157528-ec4018b0-7dbb-11e8-9319-184b02335ced.png)

**Comment by fourtf** [comment] 2018-07-02 10:29
Could you describe what the issue is and rename this issue accordingly? I would assume that the issue is images not showing?

**Comment by LajamerrMittesdine** [comment] 2018-07-02 11:54
@fourtf I'm not entirely sure how to describe this issue. There's multiple things wrong besides images not showing.

The spacing between the words. The spacing between the names and the words. The spacing between the time and username.

The split header goes missing as well. 

And like you said badges, emotes, emojis and everything else goes missing.

**Comment by LajamerrMittesdine** [comment] 2018-07-03 02:06
This isn't all that happens though @fourtf the entire UI messes up.

I made a video as it happened today again.

https://gfycat.com/gifs/detail/TediousMagnificentBurro

**Comment by fourtf** [comment] 2018-08-15 22:37
Closing this until there is information on how to this bug.

**Closed by fourtf** 2018-08-15 22:37 UTC
Labels: bug
