### ISSUE TITLE
O.o smiley is displayed as hyperlink

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#549] opened 2018-07-01 15:16 UTC
![grafik](https://user-images.githubusercontent.com/16636423/42135909-5e6a5280-7d52-11e8-9da8-3290534214b5.png)

**Comment by pajlada** [comment] 2018-07-01 15:44
Fixed by lajamerr in #533 - should be included in the next beta

**Comment by LajamerrMittesdine** [comment] 2018-07-01 16:20
Just another note in case it comes up after the next beta. O.O O.o o.O o.o are all converted to that emoji face by FFZ/BTTV. Normal Twitch chat doesn't turn them into that face emote. Only O_O O_o o_O o_o is converted naturally.

**Comment by TranRed** [comment] 2018-07-01 17:30
I'm pretty sure I don't have any extensions installed on this pc rn. Converting all of these variants works for me.

![grafik](https://user-images.githubusercontent.com/16636423/42137004-40076c98-7d65-11e8-9d20-336753b77673.png)

**Comment by LajamerrMittesdine** [comment] 2018-07-02 04:44
@TranRed You most likely have BTTV installed in the left chat.

The left side is just BTTV, middle is chatterino, the right side is just normal twitch chat with no extensions.

![image](https://user-images.githubusercontent.com/2313104/42145748-0f1ceeb0-7d91-11e8-8092-1d985b291a80.png)

**Comment by TranRed** [comment] 2018-07-02 05:11
I 100% don't have bttv @LajamerrMittesdine, but I figured something out:
First Message sent through chatterino2 , second one send through the web page:

![grafik](https://user-images.githubusercontent.com/16636423/42146261-f867da8c-7dc6-11e8-9453-6b2059b7706e.png)

**Comment by pajlada** [comment] 2018-07-02 08:41
I'll reopen since the discussion following me closing the issue is interesting and relevant

**Comment by fourtf** [comment] 2018-07-02 18:35
the issue was reported to twitch by @pajlada

**Closed by fourtf** 2018-07-02 18:35 UTC
Labels: discussion
