### ISSUE TITLE
Lots of hosting messages when reconnecting after internet outage

### ISSUE THREAD

**Issue by Chronophylos** [fourtf/chatterino2#629] opened 2018-07-18 14:49 UTC
![](https://i.imgur.com/6nrV6BU.png)

**Comment by notheowner** [comment] 2018-07-18 21:39
#566

**Comment by fourtf** [comment] 2018-07-23 13:32
duplicate of https://github.com/fourtf/chatterino2/issues/566

**Closed by fourtf** 2018-07-23 13:32 UTC
