### ISSUE TITLE
Adding possibility to launch new instance/card through command parameters

### ISSUE THREAD

**Issue by sadiablos** [fourtf/chatterino2#136] opened 2017-11-19 02:30 UTC
Possibility to launch chatterino with something like "-c monstercat" which would open new instance/new card/make active opened one that would help integrate this as an option for Streamlink Twitch GUI

**Comment by fourtf** [comment] 2018-01-05 03:37
duplicate of #136

**Closed by fourtf** 2018-01-05 03:37 UTC
Labels: enhancement

**Comment by sadiablos** [comment] 2018-03-18 23:25
Wait, what?

**Comment by Yardanico** [comment] 2018-03-19 04:57
Lol

**Comment by fourtf** [comment] 2018-03-19 10:21
Changed the link of the duplicate issue in my last post.

Thanks for insightful comments such as "Wait, what?" and "Lol", very helpful.
