### ISSUE TITLE
Personal BTTV emotes don't work

### ISSUE THREAD

**Issue by Pal2X** [fourtf/chatterino2#956] opened 2019-02-14 12:08 UTC

**Comment by gapbl4** [comment] 2019-02-14 12:41
yes

**Comment by TranRed** [comment] 2019-02-20 07:50
duplicate of #12 NaM

**Comment by pajlada** [comment] 2019-02-20 08:41
Yup, what @tranred said, duplicate of #12

**Closed by pajlada** 2019-02-20 08:41 UTC

**Comment by Pal2X** [comment] 2019-03-01 17:04
That was 2 years ago

**Comment by gapbl4** [comment] 2019-03-01 19:12
and it still open, so no point in duplicate
