### ISSUE TITLE
Freeze: On faster chat auto completion freezes Chatterino completely

### ISSUE THREAD

**Issue by SFFan123** [fourtf/chatterino2#551] opened 2018-07-01 22:58 UTC
I was is sodapoppins chat during sellout Sunday I wanted to autocomplete ppHop and on the keydown of tab it completly freezes.

**Comment by notheowner** [comment] 2018-07-01 23:17
Can confirm this, but in general, not just fast chat room, tab-complete is extremely laggy or crashes Chatterino mostly in chat rooms that have a lot of chatters

**Comment by LajamerrMittesdine** [comment] 2018-07-02 04:52
This issue seems related to both #545 and #405

**Comment by SFFan123** [comment] 2018-07-02 09:57
I got no high cpu usage by chatterino before/while freeze, not like in #545. Only 12% of a i7-3770K.

**Comment by fourtf** [comment] 2018-07-02 17:04
Duplicate of #545

@SFFan123 12% in the task manager on your CPU means that the application is using an entire processor thread. (4 cores => 8 threads with hyper-threading)

**Closed by fourtf** 2018-07-02 17:04 UTC
