### ISSUE TITLE
feature request: links to join / add new split for hosted channels

### ISSUE THREAD

**Issue by Confuseh** [fourtf/chatterino2#837] opened 2018-10-26 20:32 UTC
i dont wanna press ctrl+r and put in the channel name when with this feature i would be able to just click :slightly_smiling_face: 

![suggestion](https://puu.sh/BRsyQ/ca290e6073.png)

**Comment by apa420** [comment] 2018-10-26 21:15
Duplicate to some extent of #787

**Comment by fourtf** [comment] 2018-10-29 20:53
Closing because it's a duplicate of https://github.com/fourtf/chatterino2/issues/787

**Closed by fourtf** 2018-10-29 20:53 UTC
