### ISSUE TITLE
Cycling through emotes via tabbing includes only global emotes

### ISSUE THREAD

**Issue by bennyhillthebest** [fourtf/chatterino2#251] opened 2018-01-20 13:44 UTC
I am unable to select FFZ and BTTV channel-only emotes via tabbing. I am unsure about sub emotes.

**Comment by fourtf** [comment] 2018-01-20 17:59
duplicate of https://github.com/fourtf/chatterino2/issues/251

**Closed by fourtf** 2018-01-20 17:59 UTC

**Comment by bennyhillthebest** [comment] 2018-01-21 13:08
Duplicate of #251? It is #251...

**Comment by fourtf** [comment] 2018-01-21 13:10
Sport I meant #186
