### ISSUE TITLE
Feature: Add search function for emotes

### ISSUE THREAD

**Issue by SFFan123** [fourtf/chatterino2#512] opened 2018-06-24 12:31 UTC
A search function so you can find emotes and emojis faster/better the hundreds of emotes/emojis you have. 

Like the default twitch search window:
![search1](https://user-images.githubusercontent.com/38184195/41819003-b9e0d29a-77b9-11e8-9284-f09eb5e23163.PNG)

And/Or this search function that gets triggered by ":" in the beginning. 
![search2](https://user-images.githubusercontent.com/38184195/41819004-b9fbcf00-77b9-11e8-950a-d2045ce84787.PNG)

The serach **should** do always contains() and not startsWith() since startsWith() won't help if you only know the last letters of the emote but not the prefix ...

**Comment by fourtf** [comment] 2018-08-15 22:47
duplicate of an issue that I made

**Closed by fourtf** 2018-08-15 22:47 UTC
Labels: enhancement
