### ISSUE TITLE
login issue 

### ISSUE THREAD

**Issue by Ventus1337** [fourtf/chatterino2#971] opened 2019-03-06 00:17 UTC
one day i had the issue where i got dissconnected and reconnected from chat many times .
i redownloaded chatterino ( 1 ) like 5 times to fix it . 
but after the 5th time i couldnt log in anymore 
under the login button it said .
: Could not open tcp port 5215 , Try the login via fourtf.com instead! : 
(i also couldnt click the login button anymore ) 
im thankfull for any advice

**Comment by hemirt** [comment] 2019-05-05 15:09
this seems like an issue from chatterino 1, this repository is for chatterino 2

the issue could be with wrong password or expired tokens and stuff like that

the port issue could be caused by another app occupying the 5215 tcp port for its own use, you would have to check with some network monitoring apps

@pajlada close, this is old anyways and w(sh)ould be "randomly" fixed by restarting pc or waiting some time

**Comment by pajlada** [comment] 2019-05-06 10:05
@Ventus1337 To reiterate what hemirt said, what you posted is an issue about Chatterino 1. If you want, you can try out Chatterino2 and see if that works better for you.
https://github.com/fourtf/chatterino2/releases/tag/nightly-win

**Closed by pajlada** 2019-05-06 10:05 UTC
