### ISSUE TITLE
Ability to hover over a link and show the embed information?

### ISSUE THREAD

**Issue by azgoodaz** [fourtf/chatterino2#633] opened 2018-07-20 19:03 UTC
A nice feature to prevent streamers from getting trolled, etc.

I would be nice to hover over a link and show the embed image, for example like you hover over a YouTube video link an a embed shows up with the name, channel name and thumbnail show.

**Comment by fourtf** [comment] 2018-07-23 13:20
Duplicate of another issue.

**Closed by fourtf** 2018-07-23 13:20 UTC
