### ISSUE TITLE
Hotkeys for moderation actions on user info panel

### ISSUE THREAD

**Issue by 0xRainy** [fourtf/chatterino2#848] opened 2018-10-29 17:40 UTC
Greatly improve moderation speed and accuracy by allowing keybinds for moderation actions in the user info panel when clicking on a username.

Currently it works like this:

Click on username
User Info panel opens
Click on moderation action
Click into chat window again so that the User Info panel goes away so you can click on another username (because it always opens directly over the chat window)
Repeat

With keybinds in user info panel it would work like this:

Click on username
User Info panel opens
Press [keybind] and trigger moderation action (Such as "3" -> 10min timeout)
User Info panel closes

Trying to click on the moderation icons while a chat is moving is not as accurate as this method, even with chat paused. It allows for confirmation that you got the right user and keeps the chat lines as small as possible by not having multiple icons in front of all usernames and offers much more options for timeout length.

Removing a mouse movement away from the chat to click on a timeout option in the user panel would increase moderation reaction time and accuracy. With this new method all you have to do is Click and Press a button, then move on to the next user.

**Comment by fourtf** [comment] 2018-10-29 19:04
Probably a duplicate of https://github.com/fourtf/chatterino2/issues/353

Please complain if it isn't.

**Closed by fourtf** 2018-10-29 19:04 UTC
